// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTRYzzYodzRvLnDQVNLeTfudukPyn_isE',
    appId: '1:920485328992:android:a7ce17fa43ff131a17ab05',
    messagingSenderId: '920485328992',
    projectId: 'piffers-app-sos',
    storageBucket: 'piffers-app-sos.firebasestorage.app',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB31U09vXUZls9tAOYwqJy8Qm7ShGAK2EM',
    appId: '1:920485328992:ios:7fc5636327d6e24217ab05',
    messagingSenderId: '920485328992',
    projectId: 'piffers-app-sos',
    storageBucket: 'piffers-app-sos.firebasestorage.app',
    iosBundleId: 'com.example.piffers',
  );
}
